# Generated by Django 5.2.1 on 2025-05-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="recipe_link",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="menu/"),
        ),
    ]
